version: '3'
services:
  db:
    container_name: mxdb
    image: mysql:latest
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    
  mendixapp:
    container_name: mendixapp
    image:  gopirapid07/rapidlease:12
    restart: always
    depends_on: 
      - db
    ports:
      - 8083:8080
    links:
      - 'db:gopirapid07/rapidlease:12'  
    environment:
      - ENV_HOME=/opt/mendix/build
      - ENV_PYTHONPATH=/opt/mendix/buildpack/lib/:/opt/mendix/buildpack/:/opt/mendix/buildpack/lib/python3.6/site-packages/
      - ENV_NGINX_CUSTOM_BIN_PATH=/usr/sbin/nginx
        
