version: '3.1'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    
  mendixapp:
    image:  gopirapid07/rapidlease:12
    restart: always
    depends_on: 
      - db
    ports:
      - 8083:8080
    links:
      - 'db:db'  
    environment:
      - ENV HOME=/opt/mendix/build
      - ENV PYTHONPATH=/opt/mendix/buildpack/lib/:/opt/mendix/buildpack/:/opt/mendix/buildpack/lib/python3.6/site-packages/
      - ENV NGINX_CUSTOM_BIN_PATH=/usr/sbin/nginx
        